osx_image: xcode8.3
language: objective-c
sudo: required 


scrpipt:
  - xcodebuild clean build test
    -project "FastcampusFrame2.xcodeproj"
    -scheme "FastcampusFrame2"
    -sdk "iphonesimulator10.3"
    -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1"
    -configuration Release
    -enableCodeCoverage YES
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO